import { Activity, AlertCircle, CheckCircle2, ChevronsDownUp, ChevronsUpDown, Clock3, RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getAgentDashboard, resolveFlashcard } from '../../api/client';
import type { AgentDashboard, PatientFlashcard, PatientTimelineEvent, UrgencyCategory } from '../../types/careflow';

const urgencyStyles: Record<UrgencyCategory, string> = {
  CRITICAL: 'bg-rose-100 text-rose-800 ring-rose-200',
  HIGH: 'bg-amber-100 text-amber-800 ring-amber-200',
  MEDIUM: 'bg-sky-100 text-sky-800 ring-sky-200',
  LOW: 'bg-indigo-100 text-indigo-800 ring-indigo-200',
};

interface AgentDashboardPanelProps {
  refreshSignal?: number;
}

function formatLabel(value: string) {
  return value
    .split('_')
    .map((part) => part.charAt(0) + part.slice(1).toLowerCase())
    .join(' ');
}

function formatRelativeTime(value: string) {
  const minutes = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60_000));
  if (minutes < 1) {
    return 'Now';
  }
  if (minutes < 60) {
    return `${minutes}m`;
  }
  const hours = Math.floor(minutes / 60);
  return `${hours}h ${minutes % 60}m`;
}

export function AgentDashboardPanel({ refreshSignal = 0 }: AgentDashboardPanelProps) {
  const [dashboard, setDashboard] = useState<AgentDashboard>({ flashcards: [], timeline: [] });
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [resolverName, setResolverName] = useState('Care team');
  const [resolvingId, setResolvingId] = useState<string | null>(null);
  const [expandedCardId, setExpandedCardId] = useState<string | null>(null);

  const loadDashboard = useCallback(async () => {
    setError(null);
    try {
      setDashboard(await getAgentDashboard());
    } catch (caughtError) {
      setError(caughtError instanceof Error ? caughtError.message : 'Unable to load agent dashboard.');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    setIsLoading(true);
    void loadDashboard();
  }, [loadDashboard, refreshSignal]);

  useEffect(() => {
    const intervalId = window.setInterval(() => void loadDashboard(), 10_000);
    return () => window.clearInterval(intervalId);
  }, [loadDashboard]);

  const openCards = useMemo(() => dashboard.flashcards.filter((flashcard) => !flashcard.resolved), [dashboard.flashcards]);
  const resolvedCards = useMemo(() => dashboard.flashcards.filter((flashcard) => flashcard.resolved), [dashboard.flashcards]);

  const handleResolve = async (flashcard: PatientFlashcard) => {
    setResolvingId(flashcard.id);
    setError(null);

    try {
      await resolveFlashcard(flashcard.id, resolverName);
      await loadDashboard();
    } catch (caughtError) {
      setError(caughtError instanceof Error ? caughtError.message : 'Unable to resolve flashcard.');
    } finally {
      setResolvingId(null);
    }
  };

  return (
    <section aria-labelledby="agent-dashboard-title" className="border-b border-sky-100 pb-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-medium text-sky-700">Care agent</p>
          <h2 id="agent-dashboard-title" className="mt-1 text-2xl font-semibold text-slate-950">
            Assignment cards
          </h2>
          <p className="mt-1 text-sm text-slate-500">Open patient work generated by the care agent</p>
        </div>

        <div className="flex flex-col gap-2 sm:flex-row sm:items-end">
          <label className="text-sm font-medium text-slate-700">
            Resolved by
            <input
              value={resolverName}
              onChange={(event) => setResolverName(event.target.value)}
              className="input-field mt-1"
              placeholder="Staff name"
            />
          </label>
          <button
            type="button"
            onClick={() => void loadDashboard()}
            disabled={isLoading}
            className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-sky-200 bg-white px-3 text-sm font-medium text-slate-800 shadow-sm transition hover:bg-sky-50 disabled:cursor-not-allowed disabled:opacity-60"
          >
            <RefreshCw size={16} className={isLoading ? 'animate-spin' : ''} aria-hidden="true" />
            Refresh
          </button>
        </div>
      </div>

      {error ? (
        <div className="mt-5 flex items-start gap-3 rounded-md border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">
          <AlertCircle size={18} className="mt-0.5 shrink-0" aria-hidden="true" />
          <p>{error}</p>
        </div>
      ) : null}

      <div className="mt-5 grid gap-4 xl:grid-cols-[1.15fr_0.85fr]">
        <div className="grid gap-3 md:grid-cols-2">
          {isLoading ? (
            Array.from({ length: 4 }).map((_, index) => <FlashcardSkeleton key={index} />)
          ) : openCards.length === 0 ? (
            <EmptyPanel label="No agent flashcards yet." />
          ) : (
            openCards.map((flashcard) => (
              <Flashcard
                key={flashcard.id}
                flashcard={flashcard}
                expanded={expandedCardId === flashcard.id}
                isResolving={resolvingId === flashcard.id}
                onResolve={() => void handleResolve(flashcard)}
                onToggleExpand={() => setExpandedCardId((current) => (current === flashcard.id ? null : flashcard.id))}
              />
            ))
          )}
          {!isLoading && resolvedCards.length > 0 ? (
            <div className="rounded-lg border border-indigo-100 bg-indigo-50 p-4 text-sm text-indigo-900 md:col-span-2">
              {resolvedCards.length} resolved card{resolvedCards.length === 1 ? '' : 's'} in the current view.
            </div>
          ) : null}
        </div>

        <div className="rounded-lg border border-sky-100 bg-white p-4 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <h3 className="text-sm font-semibold text-slate-950">Patient timeline</h3>
            <Activity size={18} className="text-sky-700" aria-hidden="true" />
          </div>

          <div className="mt-4 space-y-3">
            {isLoading ? (
              Array.from({ length: 5 }).map((_, index) => <TimelineSkeleton key={index} />)
            ) : dashboard.timeline.length === 0 ? (
              <p className="rounded-md border border-sky-100 bg-sky-50 p-4 text-sm text-slate-500">
                No timeline events yet.
              </p>
            ) : (
              dashboard.timeline.map((event) => <TimelineItem key={event.id} event={event} />)
            )}
          </div>
        </div>
      </div>
    </section>
  );
}

function Flashcard({
  expanded,
  flashcard,
  isResolving,
  onResolve,
  onToggleExpand,
}: {
  expanded: boolean;
  flashcard: PatientFlashcard;
  isResolving: boolean;
  onResolve: () => void;
  onToggleExpand: () => void;
}) {
  return (
    <article className={`rounded-lg border border-sky-100 bg-white p-4 shadow-sm transition ${expanded ? 'md:col-span-2' : ''}`}>
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-xs font-semibold uppercase tracking-normal text-slate-500">{flashcard.patientDisplayId}</p>
          <h3 className="mt-1 text-base font-semibold text-slate-950">{flashcard.title}</h3>
        </div>
        <span
          className={`inline-flex shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${urgencyStyles[flashcard.urgencyCategory]}`}
        >
          {formatLabel(flashcard.urgencyCategory)} {flashcard.urgencyScore}
        </span>
      </div>

      <p className="mt-3 text-sm leading-6 text-slate-600">{flashcard.summary}</p>

      {expanded ? (
        <div className="mt-4 grid gap-3 rounded-md border border-sky-100 bg-sky-50 p-3 sm:grid-cols-3">
          <FlashcardFact label="Assigned" value={flashcard.assignedStaffName ?? formatLabel(flashcard.audienceRole)} />
          <FlashcardFact label="Department" value={flashcard.department} />
          <FlashcardFact label="Status" value={formatLabel(flashcard.status)} />
          <FlashcardFact label="Patient" value={flashcard.patientDisplayId} />
          <FlashcardFact label="Action" value={flashcard.actionLabel} />
          <FlashcardFact label="Updated" value={formatRelativeTime(flashcard.updatedAt)} />
        </div>
      ) : null}

      <div className="mt-4 flex items-center justify-between gap-3 border-t border-sky-100 pt-3">
        <div className="text-xs text-slate-500">
          <p className="font-semibold text-slate-700">{flashcard.assignedStaffName ?? formatLabel(flashcard.audienceRole)}</p>
          <p>{formatLabel(flashcard.status)} - {flashcard.actionLabel}</p>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          <button
            type="button"
            onClick={onToggleExpand}
            className="inline-flex h-9 w-9 items-center justify-center rounded-md border border-sky-200 bg-white text-slate-800 transition hover:bg-sky-50"
            aria-label={expanded ? 'Fold flashcard' : 'Expand flashcard'}
            title={expanded ? 'Fold' : 'Expand'}
          >
            {expanded ? <ChevronsDownUp size={15} aria-hidden="true" /> : <ChevronsUpDown size={15} aria-hidden="true" />}
          </button>
          <button
            type="button"
            onClick={onResolve}
            disabled={isResolving}
            className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-slate-950 px-3 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
          >
            <CheckCircle2 size={15} aria-hidden="true" />
            {isResolving ? 'Saving' : 'Resolve'}
          </button>
        </div>
      </div>
    </article>
  );
}

function FlashcardFact({ label, value }: { label: string; value: string }) {
  return (
    <div className="min-w-0 rounded-md bg-white p-3">
      <p className="text-xs font-semibold uppercase tracking-normal text-slate-500">{label}</p>
      <p className="mt-1 truncate text-sm font-medium text-slate-800">{value}</p>
    </div>
  );
}

function TimelineItem({ event }: { event: PatientTimelineEvent }) {
  return (
    <article className="rounded-md border border-sky-100 bg-sky-50 p-3">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-sm font-semibold text-slate-950">{event.title}</p>
          <p className="mt-1 text-xs font-medium text-slate-500">
            {event.patientDisplayId} - {event.source === 'AGENT' ? 'CareFlow Agent' : event.actorName ?? 'Staff'}
          </p>
        </div>
        <span className="inline-flex shrink-0 items-center gap-1 text-xs font-medium text-slate-500">
          <Clock3 size={13} aria-hidden="true" />
          {formatRelativeTime(event.createdAt)}
        </span>
      </div>
      <p className="mt-2 text-sm leading-6 text-slate-600">{event.description}</p>
    </article>
  );
}

function EmptyPanel({ label }: { label: string }) {
  return (
    <div className="rounded-lg border border-sky-100 bg-white p-6 text-center text-sm text-slate-500 shadow-sm md:col-span-2">
      {label}
    </div>
  );
}

function FlashcardSkeleton() {
  return (
    <article className="rounded-lg border border-sky-100 bg-white p-4 shadow-sm">
      <div className="h-4 w-24 animate-pulse rounded bg-sky-100" />
      <div className="mt-3 h-5 w-3/4 animate-pulse rounded bg-sky-100" />
      <div className="mt-4 h-16 animate-pulse rounded bg-sky-100" />
    </article>
  );
}

function TimelineSkeleton() {
  return (
    <div className="rounded-md border border-sky-100 bg-sky-50 p-3">
      <div className="h-4 w-2/3 animate-pulse rounded bg-sky-100" />
      <div className="mt-3 h-10 animate-pulse rounded bg-sky-100" />
    </div>
  );
}
